apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate
spec:
   replicas: 2
   selector:
      matchLabels:
        app: podnm
   strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
   minReadySeconds: 10
   template:
      metadata:
        name: kalu
        labels:
           app: podnm
      spec:
        containers:
        - name: cntnm


          image: raparthikalyan/kal-boot-mongo
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hpaclusterservice
  labels:
    name: hpaservice
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: podnm
  type: NodePort
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollingupdate
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource                           
